[package]
name = "agave-event-system"
description = "A local pub-sub system used by agave validators to publish events to outside processes."
documentation = "https://docs.rs/agave-event-system"
version = "0.2.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[dependencies]
agave-event-system-derive = { workspace = true }
thiserror = { workspace = true }
wincode = { workspace = true }
wincode-dynamic = { workspace = true, features = ["derive"] }

[target.'cfg(target_os = "linux")'.dependencies]
getrandom = { workspace = true, features = ["std"] }
libc = { workspace = true }
nix = { workspace = true, features = ["dir", "time"] }
shaq = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
